services:
  - type: web
    name: backend-tres-go
    runtime: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm run start:prod
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.lsscbhiojipxvybzpciy:j5LHjVtkOJcZTUOH@aws-0-us-west-2.pooler.supabase.com:6543/postgres?pgbouncer=true
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_TLS
        value: "true"
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
